MASTER_TEMPLATE = """
<DISPLAY_BOOKMARKS>
  <SNAPSHOT>
    <NAME>default</NAME>
    <TITLE_DISPLAY_INFO>
      <VISIBLE>T</VISIBLE>
      <X_PERCENT>2</X_PERCENT>
      <Y_PERCENT>2</Y_PERCENT>
      <WIDTH_PERCENT>7.79603863</WIDTH_PERCENT>
      <HEIGHT_PERCENT>3.40172791</HEIGHT_PERCENT>
      <FONTHEIGHT_PERCENT>2.0999999</FONTHEIGHT_PERCENT>
      <TEXT_CLR_RGB>255,255,255</TEXT_CLR_RGB>
    </TITLE_DISPLAY_INFO>
    <NUM_FRAMES>10</NUM_FRAMES>
    <BREAKER>F</BREAKER>
    <CURRENT_SEISMIC>0</CURRENT_SEISMIC>
    <CURRENT_ATTRIBUTE>-1</CURRENT_ATTRIBUTE>
    <CURRENT_HORIZONGROUP>-1</CURRENT_HORIZONGROUP>
    <CURRENT_HORIZON>-1</CURRENT_HORIZON>
    <CURRENT_CIGPICKVOL>-1</CURRENT_CIGPICKVOL>
    <SEISMIC_VISIBILITY>{seismic_visible}</SEISMIC_VISIBILITY>
    <ATTRIBUTE_VISIBILITY>{attribute_visible}</ATTRIBUTE_VISIBILITY>
    <CIGPICK_VISIBILITY>{cigpick_visible}</CIGPICK_VISIBILITY>
    <HORIZON_VISIBILITY>{horizon_visible}</HORIZON_VISIBILITY>
    <WELL_VISIBILITY>{well_visible}</WELL_VISIBILITY>
    <MISC_PLOT_VISIBILITY>{misc_plot_visible}</MISC_PLOT_VISIBILITY>
    <PROFILE_VISIBILITY>{profile_visible}</PROFILE_VISIBILITY>
    <SEISMIC_COLORMAP>
      <SPECTRUM>
        <COLORMAP_NAME>Gray Scale</COLORMAP_NAME>
        <COLORMAP_INDEX>{seismic_colormap_index}</COLORMAP_INDEX>
        <TIMES>{seismic_times}</TIMES>
        <RANGE>{seismic_range_min} {seismic_range_max}</RANGE>
        <RANGE_IS_DEFAULT>F</RANGE_IS_DEFAULT>
        <LABEL> </LABEL>
        <UNIT> </UNIT>
        <ALPHA_MODE>0</ALPHA_MODE>
        <PARAM_ALPHA>0 0 255 0</PARAM_ALPHA>
        <IS_NOVALUE_TRANSPARENT>F</IS_NOVALUE_TRANSPARENT>
        <LEGEND_HAS_OPACITY>F</LEGEND_HAS_OPACITY>
        <ALPHA_TABLE>65535,65535,...</ALPHA_TABLE>
      </SPECTRUM>
    </SEISMIC_COLORMAP>
    <!-- (Other colormap sections omitted for brevity) -->
    <ORIENT>{orient0} {orient1} {orient2}</ORIENT>
    <SHIFT>{shift0} {shift1} {shift2}</SHIFT>
    <SCALE>{scale0} {scale1}</SCALE>
    <X>
      <VISIBLE>{x_visible}</VISIBLE>
      <POSITION>{x_position}</POSITION>
    </X>
    <Y>
      <VISIBLE>{y_visible}</VISIBLE>
      <POSITION>{y_position}</POSITION>
    </Y>
    <Z>
      <VISIBLE>{z_visible}</VISIBLE>
      <POSITION>{z_position}</POSITION>
    </Z>
    <!-- (Other fields can be added as needed) -->
    <ACTIVE>T</ACTIVE>
  </SNAPSHOT>
  <MULTIPLIER>1</MULTIPLIER>
  <FILENAME_STYLE>&lt;N&gt;_snapshot&lt;N&gt;</FILENAME_STYLE>
  <FORMAT>JPEG</FORMAT>
  <QUALITY>90</QUALITY>
  <RESIZE_IMAGE>F</RESIZE_IMAGE>
  <IMAGE_SIZE>1024 768</IMAGE_SIZE>
  <ATTRSNAPSHOT>
    <ATTRPROFILE_WIN_STATUS>F</ATTRPROFILE_WIN_STATUS>
  </ATTRSNAPSHOT>
  <MAINWINDOW_SIZE>2915 2032</MAINWINDOW_SIZE>
  <VIEW3D_SIZE>2373 1852</VIEW3D_SIZE>
</DISPLAY_BOOKMARKS>
"""